package com.pumpwatch.app.domain

/**
 * Formats backtest results and advisor insights into a shareable text block.
 */
object ShareFormatter {

    fun format(
        coinSymbol: String,
        result: BacktestResult,
        insights: List<AdvisorInsight>
    ): String {
        val sb = StringBuilder()
        sb.appendLine("📊 PumpWatch Backtest Report")
        sb.appendLine("━━━━━━━━━━━━━━━━━━━━━━")
        sb.appendLine("Coin: ${coinSymbol.uppercase()}")
        sb.appendLine("Trades: ${result.totalTrades} (${result.winCount}W / ${result.lossCount}L)")
        sb.appendLine("Win Rate: ${"%.1f".format(result.winRatePercent)}%")
        sb.appendLine("Net PnL: ${if (result.totalPnlAmount >= 0) "+" else ""}$${"%.2f".format(result.totalPnlAmount)}")
        sb.appendLine("Profit Factor: ${if (result.profitFactor.isInfinite()) "∞" else "%.2f".format(result.profitFactor)}")
        sb.appendLine("Max Drawdown: ${"%.1f".format(result.maxDrawdownPercent)}%")
        sb.appendLine()

        if (result.exitReasonBreakdown.isNotEmpty()) {
            sb.appendLine("Exit Reasons:")
            result.exitReasonBreakdown.entries
                .sortedByDescending { it.value }
                .forEach { (reason, count) ->
                    sb.appendLine("  • ${reason.name.replace("_", " ")}: $count")
                }
            sb.appendLine()
        }

        if (insights.isNotEmpty()) {
            sb.appendLine("🧠 Advisor Insights:")
            insights.forEach { insight ->
                val icon = when (insight.type) {
                    InsightType.PROBLEM -> "🔴"
                    InsightType.WARNING -> "🟠"
                    InsightType.INFO -> "🔵"
                }
                sb.appendLine("$icon ${insight.title}")
                sb.appendLine("   ${insight.detail}")
                insight.suggestion?.let { sb.appendLine("   💡 $it") }
            }
        }

        sb.appendLine()
        sb.appendLine("Generated by PumpWatch")
        return sb.toString()
    }
}
